### ISSUE TITLE
TRT inference

### ISSUE THREAD

**Issue by lucianzhong** [Haiyang-W/UniTR#12]
Thanks for this great work. 
For DSVT, there is  DSVT-AI-TRT for TRT inference.
I am wondering if there is anything available for UniTR like DSVT-AI-TRT ？

**Comment by Haiyang-W** [comment]
I think this is definitely no problem, unitr and dsvt use the same partition code, backbone is the same, may need a slight change in the head.

**Comment by Haiyang-W** [comment]
Sorry for the very late reply!

**Comment by lucianzhong** [comment]
Thanks for the replay
