### ISSUE TITLE
TRT

### ISSUE THREAD

**Issue by CodeWorldChanged** [Haiyang-W/UniTR#16]
HI,
there are operators such as torch.unique not supported by trt, do you have any suggestions to solve this problem?thanks

**Comment by Haiyang-W** [comment]
You mean the torch.unique used in Transfusion Head?

**Comment by Haiyang-W** [comment]
There is no torch.unique in inference time. As for the torch.unique in Backbone, you can refer [DSVT's Implementation](https://github.com/Haiyang-W/DSVT/blob/a0ab685b573896fc4bc9a64b187bdc2b574c3741/pcdet/models/backbones_3d/dsvt.py#L264).

**Comment by CodeWorldChanged** [comment]
Thank you for your guidance。
