### ISSUE TITLE
How do you test the speed of UniTR?

### ISSUE THREAD

**Issue by liyih** [Haiyang-W/UniTR#18]
Hi haiyang,
Thanks for your awesome work. I want to know how you test the speed of UniTR, can you share the code with me. What's more when you calculate the speed of UniTR, do you consider the time cost of voxelization. Thanks!
Best

**Comment by Haiyang-W** [comment]
Use the [cache Testing](https://github.com/Haiyang-W/UniTR?tab=readme-ov-file#cache-testing), and then also cache the position embedding. Moreover, I write the speed test code based on time.time(), not the default pcdet --infer time. The randomness of the speed is very large, it is recommended that you test on your own workstation, even if the same card will have some differences.

**Comment by Haiyang-W** [comment]
Due to inaccuracies in the camera parameters of NuScenes itself, the cache can affect performance.
