### ISSUE TITLE
What's the performance on the nuScene without pre-trained on ImageNet and nuImage ?

### ISSUE THREAD

**Issue by gwenzhang** [Haiyang-W/UniTR#26]
Hi, thank you for your excellent work! Can you provide the performance of UniTR on the nuscene without the pre-trained parameters?

**Comment by gwenzhang** [comment]
Would it be possible to provide the configuration files for pretraining on nuImage and ImageNet? Alternatively, could you share which open-source framework this is based on? Any information or resources would be greatly appreciated. Thanks in advance for your help

> We haven't tried training UniTR without pre-trained parameters because using pre-trained parameters has been very common in previous work. Typically, not using pre-training lowers performance. You can experiment by adjusting the command parameters to see how it performs. If you have any more questions or need further assistance, feel free to ask.

**Comment by nnnth** [comment]
Unfortunately, the original configuration files we used for pretraining are lost. We conducted ImageNet pretraining using the [MMPretrain](https://github.com/open-mmlab/mmpretrain) and nuImage pretraining using [MMDetection3D](https://github.com/open-mmlab/mmdetection3d). For nuImage pretraining, you can refer to the configuration file at this link: [nuImage configuration](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/cam_stream/mask_rcnn_dbswin-t_fpn_3x_nuim_cocopre.py).

Both frameworks have mature configurations that you can adapt for your models and use for pretraining.

**Comment by gwenzhang** [comment]
> Unfortunately, the original configuration files we used for pretraining are lost. We conducted ImageNet pretraining using the [MMPretrain](https://github.com/open-mmlab/mmpretrain) and nuImage pretraining using [MMDetection3D](https://github.com/open-mmlab/mmdetection3d). For nuImage pretraining, you can refer to the configuration file at this link: [nuImage configuration](https://github.com/ADLab-AutoDrive/BEVFusion/blob/main/configs/bevfusion/cam_stream/mask_rcnn_dbswin-t_fpn_3x_nuim_cocopre.py).
> 
> Both frameworks have mature configurations that you can adapt for your models and use for pretraining.
Thank you so much for your help!
