### ISSUE TITLE
[ONNX,TRT]Deployment

### ISSUE THREAD

**Issue by VanderBieu** [Haiyang-W/UniTR#4]
Thank you for your excellent work. 
In your arXiv paper, there are several comparisons of performance among models. Is it possible for you to provide guides or hints on how to deploy your model?
Besides, is it possible to quantize this model in int8?

**Comment by Haiyang-W** [comment]
Thanks for your interest in our work. 

I'm sorry, I'm currently rushing the CVPR deadline. 
Because the code has undergone a major refactor with many changes, I'm considering redeploying the new code after CVPR. If you're in a hurry, I can privately send you an original version of the UniTR backbone code that converts from PyTorch to ONNX and TRT engine as a reference, but there will definitely be many inconsistencies with the new version of the code.

**Comment by VanderBieu** [comment]
Thank you for your reply. 
It is of great help if you can provide me with the reference code. Wish I could help with your progress of the conversion consistent with the new version of the code.
My email address is  xia_weihang@zijinmining.com

**Comment by Haiyang-W** [comment]
> Thank you for your reply. It is of great help if you can provide me with the reference code. Wish I could help with your progress of the conversion consistent with the new version of the code. My email address is [xia_weihang@zijinmining.com](mailto:xia_weihang@zijinmining.com)

Have sent it.

**Comment by Haiyang-W** [comment]
For more details, you can refer the [deployment of DSVT](https://github.com/Haiyang-W/DSVT#tensorrt-deployment). They are very similar.

**Comment by VanderBieu** [comment]
> For more details, you can refer the [deployment of DSVT](https://github.com/Haiyang-W/DSVT#tensorrt-deployment). They are very similar.

Thank you very much.

**Comment by barathwaj07** [comment]
Hi Haiyang,

Thanks for an awesome paper. I would be glad if you can send a copy to me as well. Would really appreciate it.  Will update you on how it goes and if I can contribute :) [banandan@alumni.cmu.edu](url)

**Comment by Haiyang-W** [comment]
> banandan@alumni.cmu.edu

Have sent it. Thanks for your future contributions. 
Wish you all the best. :)

**Comment by Mavericky-j** [comment]
Hi Haiyang, 
Thanks for your excellent work. I would be glad if you can send a deployment copy to me as well. My email is ruocheng.jia@gmail.com, thanks very much.
Have a good weekend!

**Comment by Haiyang-W** [comment]
> ruocheng.jia@gmail.com

Yeah, have sent it. :)

**Comment by CodeWorldChanged** [comment]
hi
Thanks for an awesome paper. I would be glad if you can send a copy to me as well。1107315077@qq.com

**Comment by jongsik-moon** [comment]
Hi
Could you please send the code to this mail? rhdfyd789@gmail.com

**Comment by caffreypu** [comment]
Hi,thanks for your awesome paper.
Could you please send the deployment code to me as well? 404946656@qq.com, thanks.
