### ISSUE TITLE
whether tried Camera only sensor by any chance?

### ISSUE THREAD

**Issue by mdfaheem786** [Haiyang-W/UniTR#7]
Excellent work, just wanted to know whether tried Camera only sensor by any chance?
if so how is the mAP and NDS.

As bevFusion support individual and combined, so got a doubt.

thank you in advance.

**Comment by nnnth** [comment]
Yeah, we tried Camera only sensor, got an NDS of 36.2 and mAP of 31.4, as shown in Table 4 of the paper.

**Comment by mdfaheem786** [comment]
thanks for the reply.  Can i have, only camera config file.

**Comment by Haiyang-W** [comment]
> thanks for the reply. Can i have, only camera config file.

Maybe it can't be directly executed just by controlling the config; you need to understand and modify the code. According to the UniTR+LSS version, you can simply remove the lidar input. It should be easy to modify. 

If you understand the code, I believe it will take no more than 1 hour to get it running.

**Comment by mdfaheem786** [comment]
thanks for your kindly reply and suggesting. Correct in bevFusion, they are using centerpoint head for only camera sensor and transfusion for fusion part.

thank you.

**Comment by Haiyang-W** [comment]
> thanks for your kindly reply and suggesting. Correct in bevFusion, they are using centerpoint head for only camera sensor and transfusion for fusion part.
> 
> thank you.

We are rushing some deadlines and may not be able to respond promptly. Please feel free to contact us if you have any questions. :)

Haiyang
