### ISSUE TITLE
Camera Only for bev segmentation

### ISSUE THREAD

**Issue by FlyEgle** [Haiyang-W/UniTR#8]
Hi，I want to know the camera only results on the bev segmentation for nuscenes validation. The metric is not provided in the paper and readme. 

- Are there any conclusions or metrics available in this regard? 
- How can i only use camera to do inference?

Thanks!

**Comment by nnnth** [comment]
Unfortunately, we haven't tried the camera-only setting for BEV map segmentation. 
As mentioned in [issue](https://github.com/Haiyang-W/UniTR/issues/7),  using camera only would require removing modules related to lidar and fusion in the config and making modifications to the UniTR code to skip lidar processing. Currently, we're on a tight deadline and don't have time to make these code changes. However, I believe that once you understand the code, making it accept camera only input shouldn't be too difficult.

**Comment by FlyEgle** [comment]
Thank for your replay

**Comment by nnnth** [comment]
For BEV map segmentation, we haven't tested metrics for camera-only setting. We directly modified the DSVT backbone to support multi-modal inputs, so we haven't thoroughly examined our model's performance in camera-only setting, nor have we compared it to other methods.
